In [1]:
import gdown

In [2]:
!gdown 1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF -O ./data/

Using cookies from /Users/santhoshrishimarkonda/.cache/gdown/cookies.txt
Downloading...
From: https://drive.google.com/uc?id=1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF
To: /Users/santhoshrishimarkonda/Desktop/Code/CODINGWISE/Case Studies/Numpy/FitBitHealth/data/fitness.txt
100%|██████████████████████████████████████| 3.14k/3.14k [00:00<00:00, 4.18MB/s]


In [3]:
import numpy as np
fitbit = np.loadtxt("./data/fitness.txt", dtype='str')

/var/folders/9d/wpwypcv12zg9jyyfkr752bdr0000gn/T/ipykernel_38263/2709002512.py:2: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  fitbit = np.loadtxt("./data/fitness.txt", dtype='str')


In [4]:
fitbit[0]

array(['06-10-2017', '5464', '200', '181', '5', '0', '66'], dtype='<U10')

In [5]:
fitbit[:5]

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66']],
      dtype='<U10')

In [6]:
print(fitbit.shape)
print(type(fitbit))
print(fitbit.dtype)

(96, 7)
<class 'numpy.ndarray'>
<U10


In [7]:
fitbit.T[0] # all dates

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [8]:
fitbit.T[0].shape # 1D Array

(96,)

In [9]:
fitbit.T[1] # step counts

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [10]:
dates, step_counts, mood, calories_burned, hours_of_sleep, activity_status, weight_kgs = fitbit.T

In [11]:
mood

array(['200', '100', '100', '100', '200', '100', '100', '100', '100',
       '100', '100', '100', '300', '100', '100', '100', '100', '200',
       '200', '200', '200', '200', '200', '300', '200', '300', '300',
       '300', '300', '300', '300', '300', '200', '300', '300', '300',
       '300', '300', '300', '300', '300', '300', '300', '200', '300',
       '300', '300', '300', '300', '300', '300', '300', '300', '200',
       '100', '300', '300', '300', '300', '300', '300', '300', '100',
       '200', '200', '100', '100', '200', '200', '300', '200', '200',
       '100', '200', '100', '200', '200', '100', '100', '100', '100',
       '300', '200', '300', '200', '100', '100', '100', '200', '200',
       '100', '100', '300', '200', '200', '300'], dtype='<U10')

In [29]:
activity_status

array(['Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Active', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Inactive',
       'Inactive', 'Inactive', 'Inacti

### Type Converstions

In [13]:
step_counts = np.array(step_counts, dtype='int')
print("step_counts dtype:", step_counts.dtype)

step_counts dtype: int64


In [14]:
calories_burned = np.array(calories_burned, dtype='int')
print("calories_burned dtype:", calories_burned.dtype)

calories_burned dtype: int64


In [15]:
hours_of_sleep = np.array(hours_of_sleep, dtype='int')
print("hours_of_sleep dtype:", hours_of_sleep.dtype)

hours_of_sleep dtype: int64


In [16]:
weight_kgs = np.array(weight_kgs, dtype='int')
print("weight_kgs dtype:", weight_kgs.dtype)

weight_kgs dtype: int64


### Important Insights

In [17]:
np.unique(mood, return_counts=True)

(array(['100', '200', '300'], dtype='<U10'), array([29, 27, 40]))

In [18]:
mood[mood == '300'] = 'Happy'

In [19]:
mood[mood == '200'] = 'Neutral'

In [20]:
mood[mood == '100'] = 'Sad'

In [21]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [22]:
np.unique(mood, return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([40, 27, 29]))

In [27]:
np.unique(activity_status, return_counts=True)

(array(['Active', 'Inactive'], dtype='<U10'), array([42, 54]))

In [25]:
activity_status[activity_status == '0'] = 'Inactive'
activity_status[activity_status == '500'] = 'Active'

In [28]:
np.unique(activity_status, return_counts=True)

(array(['Active', 'Inactive'], dtype='<U10'), array([42, 54]))

### Key Insights

<span style = "color: green">
Whats the date with MAX step count ?
</span>

In [32]:
step_counts.max()

np.int64(7422)

In [34]:
step_counts.argmax()

np.int64(69)

In [ ]:
dates[step_counts == step_counts.max()]

array(['14-12-2017'], dtype='<U10')

In [39]:
print("The date with max step count:", dates[step_counts.argmax()])

The date with max step count: 14-12-2017


<span style = "color: green">
Whats the date with MIN step count ?
</span>

In [38]:
step_counts.min()

np.int64(25)

In [40]:
print("The date with min step count:", dates[step_counts.argmin()])

The date with min step count: 08-10-2017


<span style = "color: green">
Difference in Calories burned in MIN step count date vs MAX ?
</span>

In [55]:
max_cals = calories_burned[step_counts.argmax()]
min_cals = calories_burned[step_counts.argmin()]
max_cals, min_cals

(np.int64(243), np.int64(0))

In [57]:
print("Difference in Calories burned in MIN step count date vs MAX :", (max_cals - min_cals))

Difference in Calories burned in MIN step count date vs MAX : 243


<span style = "color: green">
Whats the most frequent Mood?
</span>

In [58]:
np.unique(mood, return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([40, 27, 29]))

In [64]:
for i,j in zip(*np.unique(mood, return_counts=True)):
    print(i, '-->', j)

Happy --> 40
Neutral --> 27
Sad --> 29


<span style = "color: green">
Insight:
</span><br/>
The most frequent mood is <span style = "color: yellow">
Happy
</span>

<span style = "color: green">
AVG Step counts : Happy vs Sad vs Neutral
</span>

In [71]:
happy_avg_step_count = np.mean(step_counts[mood == "Happy"])
print(f"Average step count when Mood is HAPPY: {happy_avg_step_count:.2f}")

sad_avg_step_count = np.mean(step_counts[mood == "Sad"])
print(f"Average step count when Mood is SAD: {sad_avg_step_count:.2f}")

neutral_avg_step_count = np.mean(step_counts[mood == "Neutral"])
print(f"Average step count when Mood is NEUTRAL: {neutral_avg_step_count:.2f}")

Average step count when Mood is HAPPY: 3392.72
Average step count when Mood is SAD: 2103.07
Average step count when Mood is NEUTRAL: 3153.78


<span style = "color: green">
Mood when step count < 2000 
</span>

In [74]:
np.unique(mood[step_counts < 2000], return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([13,  8, 18]))

The user is more sad during days when less steps are recorded

<span style = "color: green">
Mood when step count > 4000 
</span>

In [75]:
np.unique(mood[step_counts > 4000], return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([22,  9,  7]))

The user is more happy during days when more steps are recorded

<span style = "color: green">
Hours of sleep Happy vs Sad
</span>

In [79]:
np.unique(hours_of_sleep[mood == 'Happy'], return_counts=True)

(array([2, 4, 5, 6, 7, 8, 9]), array([ 1,  6, 13, 10,  3,  6,  1]))

In [ ]:
np.unique(np.mean(hours_of_sleep[mood == 'Happy']))

array([5.725])

In [80]:
np.unique(hours_of_sleep[mood == 'Sad'], return_counts=True)

(array([2, 3, 4, 5, 6, 7, 8]), array([1, 5, 4, 9, 5, 2, 3]))

In [78]:
np.unique(np.mean(hours_of_sleep[mood == 'Sad']))

array([5.03448276])

The Hours of sleep metric didn't project much difference

In [81]:
np.unique(np.mean(hours_of_sleep))

array([5.21875])

The user should focus on better sleep cycle