# NPS CASE STYDY

## What is NPS ?<br/>
<img src="./imgs/nps.webp" width="525"><br/><br/>
### <span style= "color : yellow"> " % of promoters - % of detractors " </span>
- Higher the NPS score => Better chance to launch **New Product**
- Lower the NPS score => Current product is under performing
```
Max value : 100%
Min value : -100%
```

In [3]:
# ! pip install --upgrade gdown

Getting Data

In [5]:
! gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK -O ./data/

Using cookies from /Users/santhoshrishimarkonda/.cache/gdown/cookies.txt
Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /Users/santhoshrishimarkonda/Desktop/Code/CODINGWISE/Case Studies/Numpy/NetPromoterScore/data/survey.txt
100%|██████████████████████████████████████| 2.55k/2.55k [00:00<00:00, 4.89MB/s]


In [6]:
import numpy as np

Loading data

In [13]:
scores = np.loadtxt("./data/survey.txt", dtype='int')
scores[:5]

array([ 7, 10,  5,  9,  9])

Type and shape checks

In [29]:
print(type(scores))
print(scores.dtype)
print(scores.shape)

<class 'numpy.ndarray'>
int64
(1167,)


Creating Detractors category

In [17]:
detractors = scores[scores <= 6]
detractors[:5]

array([5, 4, 4, 5, 1])

Creating Promoters category

In [18]:
promoters = scores[scores >= 9]
promoters[:5]

array([10,  9,  9,  9,  9])

In [21]:
detractors.shape

(332,)

In [27]:
per_of_detractors = detractors.shape[0]/scores.shape[0]
per_of_promoters = promoters.shape[0]/scores.shape[0]
print(f"Percentage of Promoters = {per_of_promoters * 100:.2f}\n\
Percentage of Detractors = {per_of_detractors * 100:.2f}\n")

Percentage of Promoters = 52.19
Percentage of Detractors = 28.45



In [28]:
NPS_score = per_of_promoters - per_of_detractors
print(f"NPS Score = {NPS_score * 100:.2f}\n")

NPS Score = 23.74



<span style = "color: red">Insight</span>
> As per the NPS Score the Project from the Organisation failed to meet the expectations and satify the customers, therefore the organisation and its people need to work the product, make it better to meet the audience expectations